name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Resources
        run: |
            cd src
            zip -r ../UniverseResources.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zip_file
          path: UniverseResources.zip
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Get latest commit hash
        id: get_commit_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get current date
        id: get_date
        run: echo "current_date=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag ${{ env.current_date }}_${{ env.commit_hash }}
          git push origin ${{ env.current_date }}_${{ env.commit_hash }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zip_file
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: UniverseResources.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.current_date }}_${{ env.commit_hash }}
          draft: false

